spring.application.name: pedidos-api

server.port: 8080
estoque.url: http://localhost:8081

management:
  tracing:
    enabled: true
    sampling.probability: 1.0
  zipkin:
   tracing:
     endpoint: http://localhost:9411/api/v2/spans

logging:
  level:
    root: INFO
    io.henriquels25.pedidorapido: TRACE

spring:
  kafka:
    bootstrap-servers: localhost:9092
  h2:
    console:
      enabled: false
  datasource:
    url: jdbc:h2:mem:testdb